### ISSUE TITLE
Revisar as extensões instaladas

### ISSUE THREAD

**Issue by dioubernardo** [joomlagovbr/joomla-3.x#10]
Existem algumas extensões que acredito não ter necessidade de estarem na distribuição padrão, por exemplo: scriptsfooter não faz nada, está com o código comentado, Autenticação - GMail e Autenticação - LDAP, Captcha - ReCaptcha, Two Factor Authentication e Usuário - Perfil estão desabilitados.
Penso eu que a distribuição padrão deveria ser a mais limpa possível, disponibilizando apenas o necessário para o ambiente funcionar.

**Comment by Halison** [comment]
Ela desabilitada não consome recurso, e o espaço ocupado e muito pouco. a
Autenticação por LDAP, gmail etc... é uma funcionalidade usada por muitos.

2015-03-10 13:57 GMT-03:00 Bernardo Silva <notifications@github.com>:

> Existem algumas extensões que acredito não ter necessidade de estarem na
> distribuição padrão, por exemplo: scriptsfooter não faz nada, está com o
> código comentado, Autenticação - GMail e Autenticação - LDAP, Captcha -
> ReCaptcha, Two Factor Authentication e Usuário - Perfil estão desabilitados.
> Penso eu que a distribuição padrão deveria ser a mais limpa possível,
> disponibilizando apenas o necessário para o ambiente funcionar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomlagovbr/joomla-3.x/issues/10>.
>



-- 
*-*

*Algumas pessoas sonham com o sucesso, outras levantam cedo e batalham para
alcançá-lo.*

Conheça um pouco do meu trabalho: halison.net  |  fb.com/webhelp  |
linkedin.com/in/halison  |   twitter.com/halisonnet

**Comment by dioubernardo** [comment]
Ok entendo que as mesmas não ocupam espaço, porem se queres ter um repositório padrão para ser utilizado por todo mundo acredito que essa instalação deva ser impecável. E não tentar prever coisas que quem sabe alguém utilize, ou utiliza ou não, caso não utilize não deve estar no padrão.

Outro exemplo é o printscreen que segue, notar quantas extensões o "descobrir" encontra.
![capturar](https://cloud.githubusercontent.com/assets/3487994/6691204/11c97da0-cca4-11e4-8fb9-4e958c9f6617.PNG)

Não me entenda mal, não estou criticando, meu objetivo é tornar o repositório o mais perfeito possível, para que todo mundo que tente utilizar, não enfrente problemas.

**Comment by tiagovtg** [comment]
Será atualizado.
