### ISSUE TITLE
Problema com a tag title

### ISSUE THREAD

**Issue by TiagoDGomes** [joomlagovbr/joomla-3.x#101]
Olá,

Andei verificando alguns portais que utilizam o portal padrão Joomla e notei que a tag ```<title>``` dos artigos mostra apenas o nome padrão do site. Quando se compartilha a URL da página em redes sociais, este detalhe torna-se bastante relevante pois o alcance de leitores diminui com título genérico. 

Exemplo: https://pasteboard.co/IdjHkxM.png (o título desejável deveria ser "_Site Secom, Portal do Planalto e Portal Brasil adotam nova identidade digital_").

Tentei encontrar a localização do problema, mas não obtive sucesso. As configurações que são aplicadas na interface administrativa não respondem ao que é esperado. 

Para contornar esse problema, abaixo está o trecho do código que apliquei no nosso portal no arquivo ```templates/padraogoverno01/index.php```:

```php
<?php 

// Este código deve ser colocado no arquivo index.php ANTES da tag <jdoc:include type="head" />

$input = JFactory::getApplication()->input;
$id = $input->getInt('id', 0);

if(
    $id > 0 
    && $input->getString('option') == 'com_content' 
    && $input->getString('view') == 'article'
) {
    $c = JTable::getInstance('content'); 
    $c->load($id);
    $cfg = JFactory::getConfig();

    // Título da página
    $title = $c->title;

    // Sistema > Configuração Global > Definições do Site > Nome do Site:
    $sitename = $cfg->get('sitename');

    // Sistema > Configuração Global > Configurações de SEO > Incluir Nome do Site no Título:
    $sitename_pagetitles = $cfg->get('sitename_pagetitles'); // Opções: 1=Antes; 2=Após; 0=Não

    if ($sitename_pagetitles == "1"){ 
       $title = "$sitename - $title";
    } else if ($sitename_pagetitles == "2"){ 
       $title = "$title - $sitename";
    } 
    // Define o nome correto da página:
    $this->setTitle($title);
} 
?>


```

Espero de alguma forma ter ajudado.

**Comment by vinnyparker** [comment]
Muito bom! eu tinha notado a mesma coisa! pode mandar o endereço do seu portal pra eu dar uma olhada?

**Comment by TiagoDGomes** [comment]
O nosso portal é o https://www.sbv.ifsp.edu.br.
