### ISSUE TITLE
Form de Contato

### ISSUE THREAD

**Issue by vinnyparker** [joomlagovbr/joomla-3.x#104]
Alguem sabe onde eu configuro o email que vai receber os emails do form de contato?

![contactform](https://user-images.githubusercontent.com/1207567/57786781-7f433500-770a-11e9-9991-7a0d9f48bb98.png)

quem recebe a informação desse item?

**Comment by tiagovtg** [comment]
no contato...

Em qua, 15 de mai de 2019 12:11, vinnyparker <notifications@github.com>
escreveu:

**Comment by vinnyparker** [comment]
rapaz, juro por Deus q eu ja procurei la e nao encontrei...... pode printar a tela?

**Comment by vinnyparker** [comment]
deixe, comi bosta aqui, ja entendi foi mals
