### ISSUE TITLE
error.php do template

### ISSUE THREAD

**Issue by darlandc** [joomlagovbr/joomla-3.x#11]
O arquivo erro.php do template padrão está com algum problema na renderização dos headers.

Ao exibir o código fonte pelo navegador, a seguinte linha aparece:
jdoc:include type="modules" name="barra-do-governo" 

E não deveria aparecer, mas sim ser renderizada certo?

Gostaria de uma luz dos amigos desenvolvedores, obrigado desde já!

**Comment by tiagovtg** [comment]
Darlan, esse erro ainda acontece?

**Comment by dioubernardo** [comment]
Olá acabei de testar e acredito que o problema persiste.

notar no html da url http://www.ouvidoria.furg.br/index.php/component/content/article?id=7171erro
 <jdoc:include type="modules" name="barra-do-governo" /> 

Abaixo temos duas capturas de tela, uma do index mostrando tudo certo e uma segundo que eu forcei a url para apresentar um artigo que não existe, nessa segunda da para notar alguns problemas com imagens e com css, o logo está com problema no caminho da imagem está faltando um "/" no inicio do src e os botoes da barra do topo de aumentar/diminuir fonte estão com problemas no css.

![index-certo](https://cloud.githubusercontent.com/assets/3487994/13785228/772b663c-eab1-11e5-8548-c37969eb8a56.PNG)
![404-com-problema](https://cloud.githubusercontent.com/assets/3487994/13785229/77334410-eab1-11e5-8ce7-3c602a7d6e4a.PNG)

As imagens não mostram mas o no rodapé do index está "Desenvolvido com o CMS de código aberto Joomla" e no roda do erro "Interface preparada para desenvolvimento com o CMS Joomla"

**Comment by tiagovtg** [comment]
Estranho, no que esta online, se voce tentar induzir esse erro, ele ao não encontrar um artigo te redireciona para home.
http://portalpadrao.joomlacalango.org/errorrrr

Mas eu sei o que esta acontecendo no seu, é que ele esta pegando a pagina de error do template ou da system(default), e provável que as duas estejam desatualizadas.

Bem facil corrigir isso, mas como disse, na acontece no portalpadrao.

Outro fato, que tenho vivenciado é desligar tudo que nao é necessário, nesse caso plugins de redirecionamento, e busca avançada. Pois deixam o site muitooo lento. 

Outra boa também é passar o login invés de gravar a sessão no banco de dados, usar nenhum pra ele gravar no php ou usar em memoria.

**Comment by dioubernardo** [comment]
URL para induzir o erro no portal padrão
http://portalpadrao.joomlacalango.org/component/content/article?id=666

**Comment by tiagovtg** [comment]
Bom dia, refiz os testes aqui, e a unica coisa que percebi é que:

Como no template esta carregando css a mais, no error, tem que replicar essa mesma chamada do css.

![image](https://cloud.githubusercontent.com/assets/573819/13813165/c1cd6494-eb5e-11e5-9500-6c1da28daad8.png)

ja a pagina de erro, so algumas diferenças no css. mas é porque houve alterações do padrão. como essse A+ A-, ai que nao tem no padrao.
![image](https://cloud.githubusercontent.com/assets/573819/13813200/033701ba-eb5f-11e5-97a5-2aa246d59223.png)

**Comment by dioubernardo** [comment]
Carrega o 404 pede para visualizar o código fonte e procura por "jdoc:include"

**Comment by tiagovtg** [comment]
Corrigido, se acharem outro problema favor reportar.
Closed!
