### ISSUE TITLE
Orientação sobre slide.

### ISSUE THREAD

**Issue by vinnyparker** [joomlagovbr/joomla-3.x#114]
Bom dia a todos, vcs tem alguma ideia ou forma de fazer com que o slide da tela principal carregue as ultimas noticia de forma automática? pq tipo do jeito q ta eu n consegui fazer....

**Comment by kokbira** [comment]
Usamos o BT Content Slider.

www.dnocs.gov.br

Adaptamos o BT Content Slider para mostrar no formato que o antigo
Ministério da Integração usava (uma notícia de destaque à esquerda e 5
últimas notícias à direita). Anteriormente exibíamos as 9 últimas notícias
3 colunas x 1 linha x 3 slides. Aparenta como a seção Fique por Dentro,
mais abaixo, só que esta tem 3 colunas x 3 linhas x 2 slides (porque temos
10 seções),

Em ter, 25 de jun de 2019 às 09:01, vinnyparker <notifications@github.com>
escreveu:

**Comment by vinnyparker** [comment]
massa. vou testar ele. E como faz pra posicionar no lugar correto? pq nesse caso eu teria q substituir o onde aparecem os banners por este novo componente? eh isso?

**Comment by kokbira** [comment]
Não usei o componente de banners, mas acredito que seja isso.

A exemplo de nosso Fique por Dentro, para facilitar o entendimento:

1. Instalar o BT Content Slider;
2. Criar um módulo do tipo BT Content Slider;
3. Título: conforme desejo (notícias, notícias internas etc.);
4. Posição: pagina-inicial;
5. Ordem: ajustar de acordo com a ordem de apresentação de elementos no
site, mas provavelmente selecionar o primeiro item para dizer que ele vem
antes (nossa ordem é notícias, notícias internas (somente logado) e fique
por dentro);
6. Navigation bar: Numbering é o que usamos, mas bullet também é legal. Só
acho que por questão de acessibilidade, não deve ser "nenhum";
7. Next Back: colocamos "sim", mas acho que dá pra viver sem;
8. Module width e module height: colocamos "auto", mas o conteúdo da janela
pode subir ou descer se o tamanho não for bem planejado;
9. Number of rows, number of cols: número de linhas e colunas. Ajustar de
acordo. Nosso fique por dentro é 3x3. Nossas noticias antigamente eram 1x3;
10. Source, Joomla categories: coloca a fonte das notícias relacionada;
11: Source, Number of articles: fornece o limite de paginação. P.ex., se vc
colocar 12 na config 1x3 ele vai dar 4 páginas, ou menos se houver menos
artigos;
12. Item layout settings, title max chars: coloca um limite no número de
caracteres exibidos para não "estourar" o limite dado no tamanho do
componente ou o conteúdo "pular" verticalmente na exibição.

Acho que já é o suficiente. Alteramos o php para dar mais funcionalidades
(ícone como vídeo do youtube, ícone como link direto para arquivo etc.) e
ajustar de acordo com o modelo do site do antigo MI (detalhes para notícia
de destaque e nas últimas notícias comuns etc.). Caso precise de ajuda
nesse sentido, avisa aí.


Em qua, 26 de jun de 2019 às 09:59, vinnyparker <notifications@github.com>
escreveu:

**Comment by vinnyparker** [comment]
nossa, muit obrgado. eu vou tentar ver isso amanha...
valeu mesmo, mt bem detalhado.
