### ISSUE TITLE
exibir filtros no k2

### ISSUE THREAD

**Issue by vinnyparker** [joomlagovbr/joomla-3.x#118]
Boa. sabe como q eu eu posso fazer para exibir  filtros das categorias de publicações no K2, quando a pessoa clica em publicações?

**Comment by vinnyparker** [comment]
eu tava querendo algo nessa pegada aqui: http://portal.mec.gov.br/component/content/?view=licitacoes&Itemid=97&limit=10&start=10

**Comment by Halison** [comment]
Olá,

Cria um menu do tipo "Lista de Categorias", na apa layout de lista vai ter essas opções que vc ta querendo.

![lista](https://user-images.githubusercontent.com/241946/68856716-fb213880-06bf-11ea-882d-bfa4b4c5f44b.png)

**Comment by vinnyparker** [comment]
valeu a dica. vou fazer isso
