### ISSUE TITLE
Submenu com problema no mobile

### ISSUE THREAD

**Issue by renataigarashi** [joomlagovbr/joomla-3.x#119]
Criei um submenu no site e na página inicial da versão mobile, não aparecem os submenus, apenas o primeiro item. Mas ao entrar nesse item, os submenus aparecem corretamente. Como corrigir?
Pra ficar mais claro, o menu é o Institucional, na página https://www.cetem.gov.br

**Comment by Halison** [comment]
![cetem](https://user-images.githubusercontent.com/241946/68856395-25bec180-06bf-11ea-95c2-623774521e31.png)
aqui ta aparecendo normal, qual o navegador que tá dando error?

**Comment by renataigarashi** [comment]
Ah sim! Está parecendo normal porque eu corrigi o problema e esqueci de encerrar aqui, rs.
