### ISSUE TITLE
Nova funcionalidade galeria de imagens

### ISSUE THREAD

**Issue by joaomarcosmareto** [joomlagovbr/joomla-3.x#13]
Criar uma galeria de imagens que no lugar das imagens, exiba em primeiro nível, a capa dos álbuns com opção de download do .zip do álbum.

Esta funcionalidade pode ser vista em: http://www2.planalto.gov.br/area-de-imprensa

**Comment by tiagovtg** [comment]
Jõao Marcos, voce criou essa funcionalidade? seria bom termos mais contribuições para o projeto joomla egov. Obrigado

**Comment by tiagovtg** [comment]
Como é um pedido, favor enviar para o email do projeto JoomlaGovBr@gmail.com
