### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by felipesoueu** [joomlagovbr/joomla-3.x#130]
Meu site está em pleno funcionamento, porém ao incluir um novo módulo, ocorre o seguinte erro:
PHP Fatal error:  Cannot declare class TmplPadraoGoverno01Helper, because the name is already in use in "DIRETORIO/templates/padraogoverno01/helper.php on line 12, referer: http://SITE

Alguém consegue me ajudar? Grato!

**Comment by renebentes** [comment]
Fala @felipesoueu, tudo bem?

Segundo a mensagem de erro você está declarando/criando uma classe que já existe como em:

```php
class TmplPadraoGoverno01Helper {

function getHtml() { }

}
```

Verifique se isto está ocorrendo.

**Comment by Eltonhard** [comment]
> Fala @felipesoueu, tudo bem?
> 
> Segundo a mensagem de erro, você está declarando/criando uma classe que já existe como em:
> 
> ```
> class TmplPadraoGoverno01Helper {
> 
> function getHtml() { }
> 
> }
> ```
> 
> Verifique se isto está ocorrendo.



> Meu site está em pleno funcionamento, porém ao incluir um novo módulo, ocorre o seguinte erro: PHP Fatal error: Cannot declare class TmplPadraoGoverno01Helper, because the name is already in use in "DIRETORIO/templates/padraogoverno01/helper.php on line 12, referer: http://SITE
> 
> Alguém consegue me ajudar? Grato!

Vc conseguiu resolver esse erro?
