### ISSUE TITLE
Após instalação, sistema não carrega: ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by murilodbva** [joomlagovbr/joomla-3.x#134]
A página inicial do sistema original JoomlaGovBr não carrega.
A falha ocorre após baixar e instalar a atual versão.

**Mensagem de erro no browser:**
> Esta página não está funcionando
> Redirecionamento em excesso por 127.0.0.1
> Tente limpar os cookies.
> ERR_TOO_MANY_REDIRECTS

**Mensagem de erro no log:**
> [error] .. FastCGI sent in stderr: "
> PHP message: PHP Notice:  Undefined index:
> pt-BR in ../plugins/system/languagefilter/languagefilter.php on line 443
> 
> PHP message: PHP Notice:  Trying to get property 'sef' of non-object
> in ../plugins/system/languagefilter/languagefilter.php on line 443"
> 
> while reading response header from upstream, client: 127.0.0.1, server: 127.0.0.1,
> request: "GET /index.php/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:",
> host: "..", referrer: "../installation/index.php"

**Solução temporária:**
1. Dentro do acesso administrativo: ../administrator/index.php
2. Desativar o plugin de linguagem: **Language Filter**
        

  Fonte da solução temporária:
    https://www.bluestonedesign.de/faq/14-extensions/552-joomla-error-err-too-many-redirects

**Comment by tiagovtg** [comment]
Acabei de fazer download do projeto aqui no github, instalar do zero, criar pasta, descompactar, criar banco de dados etc

Esta tudo funcionando normalmente, pagina principal, paginas de artigos e área administrativa.

**Comment by murilodbva** [comment]
@tiagovtg realmente você tem razão que agora está funcionando. Acabei de conferir.
De fato o erro existia, mas já não vem ao caso. Algum commit o consertou.
Eu deveria ter baixado novamente com o código atual e testado novamente antes de postar a issue.
Muito obrigado pela rapidez e atenção de sempre. =)
