### ISSUE TITLE
Switch to OAuth 2 for OpenStreetMap provider

### ISSUE THREAD

**Issue by danieldegroot2** [joomlagovbr/joomla-3.x#140]
Switch to OAuth 2 from HTTP Basic Auth and OAuth 1.0a. They are being deprecated.
See https://github.com/openstreetmap/operations/issues/867

Note, `api.openstreetmap.org` API url currently can not do OAuth 2 handshake. See https://github.com/openstreetmap/operations/issues/951#issuecomment-1748717154
You can split the `www.` base URL and `api.` API url. See https://github.com/osmlab/osm-auth/pull/123#issuecomment-1777330094

Related https://github.com/joomla/volunteers.joomla.org/issues/267

**Comment by mmd-osm** [comment]
@danieldegroot2 : this project seems to use some joomla library for OAuth 1.0a. I found something related https://github.com/joomla-framework/openstreetmap-api , which is no longer maintained.

**Comment by danieldegroot2** [comment]
Closing
