### ISSUE TITLE
O editor 'frontend' não funciona, botões 'salva' e 'cancelar' não funcionam, o botão artigo abre desconfigurado e não cria o link

### ISSUE THREAD

**Issue by julikr** [joomlagovbr/joomla-3.x#16]
Boa tarde a todos!
Ao tentar utilizar o editor frontend os botões 'salva' e 'cancelar' não funcionam. 
O botão artigo abre desconfigurado e não cria o link.
O problema é no template padraogoverno01, testei com outro template e o editor funciona.

Alguma solução?

Desde já agradeço,

**Comment by tiagovtg** [comment]
Dentro do index.php do template padrao, adicione:

defined('_JEXEC') or die;
// Add JavaScript Frameworks
JHtml::_('bootstrap.framework');

Depois no helper.php, da template padrao:

altere a parte da função:

	static function clearDefaultScripts( &$tmpl, $return = false )
	{
		$user = JFactory::getUser();
		$clear_default_javascript = $tmpl->params->get('clear_default_javascript', 0);
		$new_scripts = $scripts = $tmpl->_scripts;
		$new_script  = $script = $tmpl->_script;

		if ($clear_default_javascript == 1 && !$user->get('isRoot')) {

**Comment by tiagovtg** [comment]
Closed!
