### ISSUE TITLE
can't run finder_indexer.php from cron

### ISSUE THREAD

**Issue by barrycox** [joomlagovbr/joomla-3.x#17]
finder-indexer.php has a check to make sure you're not running from a web browser.  

however it's throwing the error 'This is a command line only application' for me when i run it as php finder_indexer.php from a cron job (which should be allowed and is probably the most common use case).  if i run the same command from the command line it works (returns 'cgi')

so i don't think 'cli' is the only possible value that should be allowed?

**Comment by barrycox** [comment]
note, when run from cron, PHP_SAPI returns 'cgi-fcgi' vs. 'cgi'.  so checking for either, or that 'cgi' is in the string (or 'apahe' is not in the string) would be a more generic way to kill the script if it's being run from the web interface.

right now i have to hack joomla to look for 'cgi' or 'cgi-fcgi' in order for it to run in my environment.

**Comment by tiagovtg** [comment]
@barrycox your issue, need to be open in a issue oficial joomla at https://issues.joomla.org/

Thx
