### ISSUE TITLE
Atualização Bootstrap v3?

### ISSUE THREAD

**Issue by renebentes** [joomlagovbr/joomla-3.x#18]
Já existe tentativas de atualização deste layout para a versão 3 do Bootstrap, tendo em vista que a versão original incluída no core Joomla está desatualizada e sem suporte por parte da equipe Bootstrap?

**Comment by tiagovtg** [comment]
Até onde eu sei, continuamos a seguir a versão do Joomla oficial que ainda mantem essa versão 2.2 Quem sabe na versão 3.5 do joomla não saia uma nova.

**Comment by renebentes** [comment]
Hum... Pelo que vi ainda está na 2.3.2.... Vamos aguardar, então...
