### ISSUE TITLE
Layout alternativo para categoria

### ISSUE THREAD

**Issue by cesarvelame** [joomlagovbr/joomla-3.x#19]
Criei uma cópia do /padraogoverno01/html/com_content/category/default.php como /padraogoverno01/html/com_content/category/eventos.php, mas só aparece o layout alternativo no gerenciador de categorias. No item de menu Lista de Categorias só aparece o tema de estilo Default. Já criei o eventos.xml como cópia do default.xml alterando o necessário, mas não quero criar um novo  tipo item de menu, somente quero o layout alternativo.

**Comment by tiagovtg** [comment]
Bom dia, tente como novo tipo de item de menu mesmo. Normalmente so módulos aceitam vários layouts, itens de menu, so duplicando. Ou to errado?

**Comment by tiagovtg** [comment]
Cesar, entendi o que vc queria fazer. Mas para criar uma nova entrada no tipo de item de menu, é no componente, nao no override dele.

Duvidas, mande para a comunidade via email.
joomlacalango@googlegroups.com

Issue são para reports de problemas.
