### ISSUE TITLE
Instalação no Xampp em localhost travando

### ISSUE THREAD

**Issue by romulolink** [joomlagovbr/joomla-3.x#20]
Ao tentar instalar o Portal padrão em joomla localmente para fins didáticos  o instalador trava na metade do processo na instalação de conteúdo conforme imagem.

http://postimg.org/image/lf0a36gmd/

**Comment by romulolink** [comment]
O problema foi contornado ao mudar o valor do parâmetro  max_execution_time de 30 para 10 no php.ini do Xampp

**Comment by tiagovtg** [comment]
Romulo, bom dia. uso muito, muito mesmo, o Portal padrão com Wamp. Tenho 15 instalaçoes locais, nenhuma deu pau.

Mudar para 10, é pior ainda. o meu é max_execution_time = 300

Deve ser outro tipo de conflito, mas que bom que conseguiu.

Precisar de ajuda, quanto ao portal, tiagovtg@gmail.com

**Comment by romulolink** [comment]
Olá Tiago!
Corrigindo; O valor foi mudado para 100 e não 10 como escrevi.
