### ISSUE TITLE
Problemas com javascript ao desinstalar o K2

### ISSUE THREAD

**Issue by fdiasmil** [joomlagovbr/joomla-3.x#21]
Estou utilizando o template padrão para um projeto na minha instituição e ao desinstalar o componente K2, as chamadas para as bibliotecas javascript são perdidas, e as mesmas não são incluídas no código. Não necessito desse componente. Há alguma solução para esse problema?
Obrigado.

**Comment by tiagovtg** [comment]
Deixe o componente ai, so ir no gerenciamento de componentes e desligar tudo.
/administrator/index.php?option=com_installer&view=manage
busque por k2, marque e despublique tudo.

**Comment by tiagovtg** [comment]
Resolvido.
