### ISSUE TITLE
Workflow para atualização do Joomla

### ISSUE THREAD

**Issue by lucaspottersky** [joomlagovbr/joomla-3.x#23]
Boa tarde,

Primeiramente queria agradecer pela iniciativa do projeto. Está fantástico.

No entanto, surgiu uma dúvida durante nossa avaliação: **como os órgãos podem realizar os updates do Joomla e ainda assim manter a compatibilidade com o projeto joomlagovbr**?

Não tenho experiência com Joomla. Aqui vai o que pensei:
- Se atualizarmos via interface Web, a instalação (ex. esquema do banco de dados) ficará diferente do JoomlaGovBR, podendo ou não haver incompatibilidades no futuro. Ou seja, não será possível integrar futuras atualizações do JoomlaGovBR à instalação que foi feita.
- Se atualizarmos baixando o código do JoomlaGovBR, o processo de instalação recria o banco de dados/tabelas do sistema. Ou seja, o conteúdo do site será perdido.

Ideias?

**Comment by tiagovtg** [comment]
Lucas, 

Após instalar o projeto Joomla/EGov, pode rodar o update automatico do joomla e dos componentes que usamos de terceiros, como phoca, k2, etc.

Nenhuma atualização fara perder dados. Veja que já esta na versão 3.4.8, acima desta somente a mais nova que é a 3.5.x

Ocorre que as alterações mais pesadas foram feitas na template ou nos overrides dos componentes e modulos, ou seja, não afeta nada do joomla original, podendo fazer update tranquilamente.

Claro que sempre, sempre, em qualquer area da informatica que se mexa com dados, se pede:
1 - fazer backup dos arquivos
2 - fazer backup do banco de dados

Agora é por prevenir, mas ja fiz muitas atualizações do egov e digo que da versão anterior a 3.2.7 para a atual e nunca tive problemas.

Att

Tiago Garcia

**Comment by tiagovtg** [comment]
Resolvido
