### ISSUE TITLE
Workflow para processamento do LESS

### ISSUE THREAD

**Issue by weslleih** [joomlagovbr/joomla-3.x#24]
Eu gostaria de saber o que vocês usaram para processar o LESS, quero ajustar algumas coisas e enviar como "pull request" para poder contribuir.
Nesse momento eu configurei um [gulp](http://gulpjs.com/) para processar o LESS na minha máquina, mas como o resultado é diferente do de vocês, achei por bem perguntar.
Se preferirem, posso enviar o pull request, com a minha configuração do gulp e explicação de como usar no readme, ao invés disso.

**Comment by fabionaka** [comment]
Usar gulp com tasks simples pra processar o less/css para manter um desenvolvimento mais limpo, acredito ser interessante.
  
acho que o pacote do template (joomlagovbr/layout) esta desatualizado em relacao ao joomla-3

**Comment by weslleih** [comment]
Considerando que o último update do [layout](https://github.com/joomlagovbr/layout) tem 3 anos... Por isso acabei postando aqui.

**Comment by tiagovtg** [comment]
Weslleih, as configurações foram feitas para compilação do Less, vc deve ter seguido as mudanças, então estou fechando essa issue.
