### ISSUE TITLE
Titulo de modulo não some ao ocultar no modulo

### ISSUE THREAD

**Issue by erickncnunes** [joomlagovbr/joomla-3.x#26]
Olá estou tendo um problema onde o titulo do modo da lateral esquerda onde existem os modulos não some. Mesmo ocultando na adm do modulo.

**Comment by tiagovtg** [comment]
Ola, 3 formas de resolver.
1 via css, hide nesse titulo.
2 via overrride de modulo
3 via alteração de codigo fonte.

Recomendo 1 ou 2.

**Comment by tiagovtg** [comment]
@erickncnunes ainda tem esse problema no titulo do modulo?

**Comment by tiagovtg** [comment]
titulo retiraram a possibilidade dele pelo admin, por causa do template, tipo para fixar.

sei que ficou ruim, mas pode mudar via css ou escolhendo outro tipo de layout de menu
