### ISSUE TITLE
Configuração das redes sociais dentro de artigo, mais especificamente facebook

### ISSUE THREAD

**Issue by warleyerocha** [joomlagovbr/joomla-3.x#28]
Boa tarde,
Como ajustar corretamente os links curtir do facebook  dentro de artigo?
Já coloquei o APPID na configuração do módulo redes sociais, mas ainda dá erro.
O link do G+ tá ok, do tiwitter funciona mas no final fica "via @portalbrasil"
Obrigado.

**Comment by tiagovtg** [comment]
Edite o modulo: Botões de compartilhamento, páginas internas.

Nele da pra configurar, data-via="portalbrasil", mude para o link que precisa, "@testeTwitter"

Outras configurações, nesse modulo ou na área administrativa, -> menu, Midias Sociais

**Comment by warleyerocha** [comment]
Show, estava pensando que era outro módulo.
Na verdade é o modulo "Botões de compartilhamento, páginas internas" e não os módulos "redes sociais".
Muito obrigado resolvi com sua ajuda.

**Comment by tiagovtg** [comment]
Closed!
