### ISSUE TITLE
mod_chamadas sem a opção de ordenação 'Ordem dos Artigos em Destaque'

### ISSUE THREAD

**Issue by ericalvim** [joomlagovbr/joomla-3.x#32]
Prezados,
Verifiquei que o **mod_chamadas** não está exibindo a ordenação dos artigos em destaque. Seria interessante ter essa ordenação via parâmetro. Tive que adicionar manualmente o join com a tabela #___content_frontpage dentro do mod_chamadas.

**Comment by tiagovtg** [comment]
eu ja tinha arrumado isso.

teste e me de um feedback
