### ISSUE TITLE
Posts na home

### ISSUE THREAD

**Issue by cheesepaulo** [joomlagovbr/joomla-3.x#37]
Opa pessoal, nas ultimas semanas adotei o portal padrão na secretaria onde trabalho. Gostaram tanto que também pediram pra usar na intranet. Só que a intranet por aqui produz pouco conteúdo e o formato atual é aquela coisa bem simples mesmo (sidebar, 1 coluna inteira pros posts e destaque no topo). Consegui desativar  o que não vou usar só falta mesmo jogar os artigos ou artigos em destaque pra home e ta resolvido meu problema.

**Comment by tiagovtg** [comment]
Paulo, isso não é um problema.
Esse espaço do issue é para reportarem problemas.
Estão na verdade é pedindo ajuda sobre duvidas.
Usem o email, mande email para a comunidade, para que possamos ajudar.
joomlacalango@googlegroups.com

Ou videos no youtube.
Caso seu é bem simples, faça com que artigos em destaques, ou categoria de artigos, seja o tipo de pagina principal.
Mude no menu, o tipo de entrada.
Hoje usamos, blank page. vc pode usar artigos, blogs, etc.
![image](https://user-images.githubusercontent.com/573819/29085673-59c434b6-7c46-11e7-99ff-0c1b86bb9fb1.png)

**Comment by cheesepaulo** [comment]
Vlw @tiagovtg :) deu certo!
