### ISSUE TITLE
Link de testes do ASES quebrado

### ISSUE THREAD

**Issue by senhordaluz** [joomlagovbr/joomla-3.x#38]
O link de testes do ASES no arquivo `joomla-3.x/templates/padraogoverno01/_testes-e-avaliacoes/LEIA-ME.md` está quebrado.

**Comment by tiagovtg** [comment]
Ola,
Faça novo teste com o Asus a partir da semana que vem por favor.
Hoje eu uso o Audit. veja #103 
Devo lançar a verção até este domingo 25/05/2019
