### ISSUE TITLE
Instala e funciona mas não instala nada

### ISSUE THREAD

**Issue by ribafs** [joomlagovbr/joomla-3.x#51]
Após instalar e corrigir os erros como sugerido eu tentei instalar alguma extensão mas veja:

Atenção
No installation plugin has been enabled. At least one must be enabled to be able to use the installer. Go to the Plugin Manager to enable the plugins.
Ao clicar no link ele não encotnra nenhum plugin com nome installer.

**Comment by ribafs** [comment]
Ops.
Acabo de mandar ele Descobrir as extensões. Descobriu muitas, inclusive os plugins de instalação. Mandei instalar todos e agora parece que tá normal.

**Comment by ribafs** [comment]
Seria bom se alguém enviasse ele já todo corrigido para cá.

**Comment by tiagovtg** [comment]
Iremos atualizar assim que possível.
