### ISSUE TITLE
Release anterior do Joomla 3.4.8 não instala

### ISSUE THREAD

**Issue by ribafs** [joomlagovbr/joomla-3.x#54]
Como encontrei muitos problemas na versão atual com o 3.7.4 então fui testar os releases anteriores.
O mais recente não instala, logo de cara aparece o erro:

Fatal error: Cannot use Joomla\String\String as String because 'String' is a special class name in /var/www/local/joomlagov_ant/libraries/vendor/joomla/registry/src/Format/Json.php on line 12

**Comment by tiagovtg** [comment]
que branch é esse?

https://github.com/joomlagovbr/joomla-3.x/branches

**Comment by tiagovtg** [comment]
Favor utilizar o branch antigo ou o atual.
Antigo 3.2.x
https://github.com/joomlagovbr/joomla-3.x/tree/3.2.x

3.7.4
https://github.com/joomlagovbr/joomla-3.x
