### ISSUE TITLE
mod_chamadas

### ISSUE THREAD

**Issue by cbdacosta** [joomlagovbr/joomla-3.x#56]
Boa noite! estou com um problema e creio que seja burrice minha, no módulo de chamadas por padrão no front-end se chama: PROGRAMA, quando clico na matéria ela não redireciona para o artigo, já verifiquei se a categoria está criada e o artigo também, está default do sistema. Alguém sabe o que pode ser mais? 

Obrigado

**Comment by cbdacosta** [comment]
Resolvido, li a issue https://github.com/joomlagovbr/joomla-3.x/issues/37

**Comment by tiagovtg** [comment]
Resolvido, li a issue #37
