### ISSUE TITLE
Menu não funciona direito em dispositivos mobile

### ISSUE THREAD

**Issue by filipeamc** [joomlagovbr/joomla-3.x#57]
Alguém sabe como resolver o problema do menu em dispositivos mobile? Quando clicamos sobre o botão do menu ela fecha inesperadamente.

**Comment by tiagovtg** [comment]
boa tarde, se puder corrigir e enviar, ou para mim ou para merge
mas eu tinha corrigido isso, nao sei se comitei. 
tiagovtg@gmail.com

**Comment by ghostnetrn** [comment]
> Alguém sabe como resolver o problema do menu em dispositivos mobile? Quando clicamos sobre o botão do menu ela fecha inesperadamente.

Comenta essa parte do código.
if( jQuery('#navigation-section').is(':visible') )
		//	jQuery('#navigation-section').hide();

**Comment by brendonalcantara97** [comment]
Sabe onde ele esta localizado qual pasta ou caminho ??
