### ISSUE TITLE
Possibilidade de tradução do menu de acessibilidade

### ISSUE THREAD

**Issue by dioubernardo** [joomlagovbr/joomla-3.x#63]
![image](https://user-images.githubusercontent.com/3487994/31142293-3f57b72a-a850-11e7-9b69-52c47fb0f3b9.png)

**Comment by tiagovtg** [comment]
Bernado sabe como criar?

Desculpa, mas o que você puder alterar e comitar seria ótimo.

Esse projeto é mantido voluntariamente, com a boa vontade de pessoas como nós.

Obrigado

**Comment by dioubernardo** [comment]
Pretendo fazer isso hoje ou amanhã, vou criar um arquivo de dicionário para
o template e vou tentar passar todos os termos que estão em português no
template para JText::_('...') da mesma forma que foi feito no com_search.




Bernardo Silva
www.bernardosilva.com.br
contato@bernardosilva.com.br

Em 16 de outubro de 2017 14:10, Tiago Garcia <notifications@github.com>
escreveu:
