### ISSUE TITLE
Como atualizar

### ISSUE THREAD

**Issue by marceloschmitt** [joomlagovbr/joomla-3.x#83]
Tenho um site no Campus Porto Alegre do IFRS funcionando (www.poa.ifrs.edu.br) há algum tempo. Atualizei o joomla por questões de segurança. A pergunta é, como faço para atualizar apenas a parte correspondente ao layout do governo? O que temos neste repositório é uma instalação completa, parece-me. O que me interessaria é apenas aquilo que diz respeito ao template (layout / barra), uma vez que o local mais apropriado para manter o joomla atualizado é no próprio repositório do joomla. 

A versão que está instalada no meu site não mostra as informações adicionais de contatos.

**Comment by tiagovtg** [comment]
Marcelo, alguém ficou de separar o tema, para um tema instalável, mas aqui no repositório não vi nada.

Agora vi seu site, me parece ja no padrão.

A barra é so vc instalar o script da barra que tem instruções no site, ou copia nosso modulo de barra e instala via descobrir. mas tem que adicionar sua chamada no index.php do seu template.

Sobre contatos, voce esta usando um artigo, e o egov usa o próprio componente de contatos.

**Comment by marceloschmitt** [comment]
Tiago

Obrigado pela agilidade. Sobre contatos, estou justamente tentando migrar daquele artigo (de fato não é um artigo, é uma URL que busca coisas fora) para os contatos. Clica em servidores (experimental)  dentro do menu institucional e clica em um nome. Não aparecem as informações adicionais embora me parece habilitado. A minha dúvida se este layout não está causando o problema. Mas é certo que para eu ter convicção disso, deveria testar com outro layout.

**Comment by renebentes** [comment]
O @dioubernardo isolou o tema, mas pelo que vi o mesmo foi renomeado e não está mais atualizado.

Penso que este tema deva ser isolado para este fim e conste na lista de repositório aqui da @joomlagovbr. Porém, nesse caso, todas as atualizações do tema seriam replicados em dois repositórios distintos.

**Comment by 1Rayzer** [comment]
Foi feita a isolação do tema para aplicar em uma atualização mais recente do joomla?

**Comment by dioubernardo** [comment]
Sim o tema foi isolado, para poder ser instalado em um ambiente novo ou existente, independente da versão do Joomla.

**Comment by marceloschmitt** [comment]
E como atualizo somente o tema? Desculpa perturbar com perguntas que podem ser simples para ti.

**Comment by tiagovtg** [comment]
Veja nesse repositório.
https://github.com/dioubernardo/pip-joomla
