### ISSUE TITLE
Problema com SSL

### ISSUE THREAD

**Issue by Lopan** [joomlagovbr/joomla-3.x#90]
Pessoal, bom dia!

Estou com um problema em habilitar o SSL no site. Toda vez que tento fazê-lo a barra não é exibida pois é retornado o seguinte erro no navegador:

`Mixed Content: The page at 'https://www3.ict.ufvjm.edu.br/' was loaded over HTTPS, but requested an insecure script 'http://barra.brasil.gov.br/barra.js?cor=verde'. This request has been blocked; the content must be served over HTTPS.`

Fiz a alteração do item mod_barradogoverno na configuração do Joomla, alterando a URL para https ao invés de http. Não deu certo. Depois alterei o arquivo xml `templates/padraogoverno01/templateDetails.xml` também para https, não deu certo.

Se retorno o site para http tudo funciona normalmente. Mas no modo HTTPS ele insiste em chamar o script da barra pelo endereço inseguro, gerando o erro no navegador.

Abraços,

**Comment by SebbaGerra** [comment]
Em templates/padraogoverno01/helper.php tem esse chamada

<script src="<?php echo $tmpl->params->get('endereco_js_barra2014'); ?>" type="text/javascript"></script><noscript>&nbsp;</noscript>

Se declarar o endereço absoluto pra

<script src="https://barra.brasil.gov.br/barra.js?cor=verde" type="text/javascript"></script><noscript>&nbsp;</noscript>

Funciona. Deve ter como chamar ela usando a variável da barra com https, mas por hora isso deve resolver
