### ISSUE TITLE
class.phpmailer.php and yandex spam

### ISSUE THREAD

**Issue by danjde** [joomlagovbr/joomla-3.x#91]
Hi Friends,
My Joomla 3.8.10 send by class.phpmailer.php one spam email by day (only one by day ore one by two days) to and from the same email "info@example.com" set on email setting.
I would like to understand if is it possible to tell to "class.phpmailer.php" not to treat the yandex addresses. Is it possible to create a sort of blacklist for  "class.phpmailer.php"?
Or anything else?

Many thanks!

Davide

**Comment by tiagovtg** [comment]
Hi Davide,

Try search for help about this, in joomla.org/forum, or in facebook community joomla.

Here in this git, is only about de template egov.

But yeah, its possible, reporting, issue, traking, create a blacklist and more else anything the programers can do. Good luck!
