### ISSUE TITLE
mod_chamada não funciona direção da ordenação

### ISSUE THREAD

**Issue by renataigarashi** [joomlagovbr/joomla-3.x#93]
Fiz uma chamada na página inicial para listar artigos k2 de uma categoria, ao escolher a ordenação ele está mudando certinho, mas a direção da ordenação não funciona, mostra sempre decrescente.

**Comment by tiagovtg** [comment]
Tem um bug no modulo chamadas que não ordena com k2.

Não é difícil corrigir

Se alguém quiser corrigir e vomitar

Não recomendo o uso do k2. O joomla não depende mais de componente externos
praticamente

Em Ter, 13 de nov de 2018 11:03, renataigarashi <notifications@github.com
escreveu:

**Comment by filipeamc** [comment]
Se livrem do K2!!!!

Em ter, 13 de nov de 2018 18:05, Tiago Garcia <notifications@github.com
escreveu:

**Comment by tiagovtg** [comment]
Ainda com problemas na ordenação? @renataigarashi
