### ISSUE TITLE
Opção de aumentar e diminuir fonte

### ISSUE THREAD

**Issue by HierraStrunger** [joomlagovbr/joomla-3.x#95]
Prezados,
Lembro que a algum tempo havia ao lado da opção alto contraste uma opção de aumentar e diminuir fonte, como neste vídeo https://www.youtube.com/watch?v=5c8PPiM7STY.
Como posso habilitá-la?

**Comment by tiagovtg** [comment]
foi instalado, os botoes de acessibilidade.
