### ISSUE TITLE
Plugin não renderiza na página

### ISSUE THREAD

**Issue by Halison** [joomlagovbr/joomla-3.x#97]
Olá amigos,

Instalei o plugin simple image gallery (https://extensions.joomla.org/extension/simple-image-gallery/) só que ele não renderiza/mostra as imagens na página usando o template padrão. Já olhei o código e não encontrei nada sobre plugin.

Alguém tem algum direcionamento, tentei ver se era alguma coisa no _clearDefaultScripts_ mas sem sucesso.
obs, quando mudo o template o plugin funciona normal.

Agradeço antecipadamente.

**Comment by tiagovtg** [comment]
Infelizmente, nem tudo eh tão simples.
O template do egov, vem com algumas alterações que quebram novos Plugins e atrapalham novas funcionalidades
Um template pronto, de graça, mas nem tudo é felicidade.
Tem que botar a mão na massa e corrigir as chamadas para seu plugin de image galley
Se conseguir fazer isso de forma até a corrigir alguma falha, pode comitar que eu reviso.
